### ISSUE TITLE
Add optional command-line arguments for `start date` and `number of days`

### ISSUE THREAD

**Issue by aaronmaxcarver** [kylesurfs/trading_data_gen#1]
- allow start date as an optional command-line argument, e.g. `python dummyDataCreator.py 2023-08-01`
  - for the default value, dynamically compute the current day's date
  - make a sensible choice (with clear documentation) for how to input the date, e.g. `2023-08-01` vs. `2023-8-1` vs. `2023-Aug-01`, etc.
- allow number of days as an optional command-line argument, e.g. `python dummyDataCreator.py 2023-08-01 45`
  - for the default value, use 7
- update README instructions

**Comment by aaronmaxcarver** [comment]
Also - suggested update to the naming scheme:

```py
words = ['Kale', 'Spinach', 'Broccoli', 'Zucchini', 'Lettuce',
         'Peas', 'GreenBean', 'Cucumber', 'Celery', 'Lime']

random_word = random.choice(words)
random_number = random.randint(0, 999)

filename = f'dummyData{random_word}{random_number}.csv'
write_to_csv(filename, headers, data)
```

resulting in names like 
`dummyDataCucumber284.csv`

**Comment by aaronmaxcarver** [comment]
Will need to update `trader_per_day`, e.g.

```py
trades_per_day = 15
headers, data = generate_dummy_data(num_days * trades_per_day)
```

Something between 10 and 100, whether static or dynamic, is probably fine

**Comment by kylesurfs** [comment]
@aaronmaxcarver please review

**Comment by aaronmaxcarver** [comment]
Nice! works great

I updated the readme:

![Screenshot 2023-08-14 at 2 46 02 PM](https://github.com/kylesurfs/trading_data_gen/assets/59704103/918f8f50-7ccb-4753-b73e-3e8a8ea1d5c7)

If that seems accurate we can close this issue

**Comment by kylesurfs** [comment]
@aaronmaxcarver Accurate, thanks. Closing issue.
